name: Create Release
on:
  milestone:
    types:
      - closed
jobs:
  close-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.milestone.title }}
          release_name: ${{ github.event.milestone.title }}
          body: ${{ github.event.milestone.description }}
          draft: false
          prerelease: false
