name: Test
on:
  pull_request:
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo -e "${{ github.event.pull_request.milestone.number }}"
