name: Test
on:
  pull_request:
    types:
      - status
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo -e "${{ github.event.pull_request.milestone.number }}"
